// Metadata is a Next.js type for the <head> tags Next.js generates automatically.
// Exporting a `metadata` object from a layout or page file is how you set
// <title>, <meta name="description">, Open Graph tags, etc. — no <Head> component needed.
import type { Metadata } from "next";

// next/font/google downloads and self-hosts Google Fonts at build time.
// This means zero external font requests at runtime — better privacy and performance.
// Geist is the sans-serif font; Geist_Mono is the monospace variant.
import { Geist, Geist_Mono } from "next/font/google";

// globals.css applies Tailwind's base/components/utilities layers to the entire app.
// It must be imported here (the root layout) so it applies to every page.
import "./globals.css";

// variable: "--font-geist-sans" creates a CSS custom property on the <body>.
// Tailwind then picks it up via the font-sans utility class.
// subsets: ["latin"] limits the downloaded characters to the Latin alphabet,
// keeping the font file small by not bundling Cyrillic, Chinese, etc.
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Next.js reads this exported object and injects the correct <title> and <meta> tags
// into the HTML <head> on every page that uses this layout.
// You should update these to match your actual app name and description.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout wraps every single page in the app — it is the one layout they all share.
// Next.js requires this file to exist at app/layout.tsx and to render <html> and <body>.
// children is whatever page (or nested layout) Next.js matched for the current URL.
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // lang="en" tells browsers and screen readers what language the page is in.
    <html lang="en">
      {/* The two CSS variables are set as classes on <body> so Tailwind's font utilities
          resolve to the self-hosted Geist fonts loaded above.
          antialiased smooths font rendering on Mac/Linux screens. */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Every page in the app renders here. The layout itself never re-mounts
            during client-side navigation — only children swap out. */}
        {children}
      </body>
    </html>
  );
}
